["East","rhsgref_faction_chdkz","rhsgref_group_chdkz_insurgents_infantry","rhsgref_group_chdkz_insurgents_squad"] call d_fnc_GetConfigGroup,
["East","rhsgref_faction_chdkz","rhsgref_group_chdkz_insurgents_infantry","rhsgref_group_chdkz_insurgents_squad"] call d_fnc_GetConfigGroup,
["East","rhsgref_faction_chdkz","rhsgref_group_chdkz_insurgents_infantry","rhsgref_group_chdkz_infantry_patrol"] call d_fnc_GetConfigGroup,
["East","rhsgref_faction_chdkz","rhsgref_group_chdkz_insurgents_infantry","rhsgref_group_chdkz_infantry_at"] call d_fnc_GetConfigGroup,
["East","rhsgref_faction_chdkz","rhsgref_group_chdkz_insurgents_infantry","rhsgref_group_chdkz_infantry_patrol"] call d_fnc_GetConfigGroup,
["East","rhsgref_faction_chdkz","rhsgref_group_chdkz_insurgents_infantry","rhsgref_group_chdkz_infantry_patrol"] call d_fnc_GetConfigGroup,
["East","rhsgref_faction_chdkz","rhsgref_group_chdkz_insurgents_infantry","rhsgref_group_chdkz_insurgents_squad"] call d_fnc_GetConfigGroup,
["East","rhsgref_faction_chdkz","rhsgref_group_chdkz_insurgents_infantry","rhsgref_group_chdkz_insurgents_squad"] call d_fnc_GetConfigGroup,
["East","rhsgref_faction_chdkz","rhsgref_group_chdkz_insurgents_infantry","rhsgref_group_chdkz_infantry_aa"] call d_fnc_GetConfigGroup
